Repository prefeitura-rio/civitas-app, pull requests merged in 2024-06, with the labels that each got.

#5 style(CercoDigital): :lipstick: Altera estilo do mapa
  src/components/CercoDigital/CercoDigital.js
Labels: Estilo

#7 Staging
  src/api.js
  src/assets/icon-atlas.png
  src/assets/logo_disque_denuncia.png
  src/assets/prefeitura_icon.png
  src/components/App.js
  src/components/AppBarNav/AppBarNav.js
  src/components/AppContainer.js
  src/components/CercoDigital/CercoDigital.js
  src/components/Login/Login.js
  src/components/Login/LoginContainer.js
  src/components/Wrapper/UnderAppBarContainer.js
  src/index.css
  src/redux/active/reducers.js
  src/redux/auth/reducers.js
  src/redux/error/reducers.js
  src/redux/sagas.js
  src/utils/SnackBar.js
  src/utils/fonte/Cera Pro Black Italic.otf
  src/utils/fonte/Cera Pro Black.otf
  src/utils/fonte/Cera Pro Bold Italic.otf
  src/utils/fonte/Cera Pro Bold.otf
  src/utils/fonte/Cera Pro Light Italic.otf
  src/utils/fonte/Cera Pro Light.otf
  src/utils/fonte/Cera Pro Medium Italic.otf
  src/utils/fonte/Cera Pro Medium.otf
  src/utils/fonte/Cera Pro Regular Italic.otf
  src/utils/fonte/Cera Pro Regular.otf
  src/utils/fonte/Cera Pro Thin Italic.otf
  src/utils/fonte/Cera Pro Thin.otf
  src/utils/formaatLocation.js
Labels: enhancement

#8 feat(CercoDigital): :sparkles: Aprimora card de informações de hover nos pontos do mapa
  package-lock.json
  package.json
  src/components/CercoDigital/CercoDigital.js
  src/index.js
Labels: Estilo, Funcionalidade

#9 fix(ConsultaDePlacas): :ambulance: Corrige erro ao tratar busca com r…
  src/components/CercoDigital/CercoDigital.js
Labels: bug

#10 fix(ConsultaDePlacas): :ambulance: Corrige misspelling
  src/components/CercoDigital/CercoDigital.js
Labels: bug

#11 fix(ConsultaDePlacas): :ambulance: Corrige erro de atualização de estado e display da listagem de viagens
  src/components/CercoDigital/CercoDigital.js
Labels: bug
